Block form when loading pair count
luomus/laji-form pull request #1
Opened 2021-03-08 13:06 UTC by aorin

Fixes an issue with water bird form where user can save a form before pair count is loaded from api.

2021-03-08 13:39 UTC, olzraiti requested changes
If the purpose of this PR is only preventing submitting the form, but not preventing the user interacting with the form, using a submit hook would be better (they don't show a blocker, but when user submits, the submit checks that all the submit hooks have completed before submitting). If the purpose is indeed preventing any user interaction, then this is ok (apart from the other comment I left)

2021-03-08 13:39 UTC, olzraiti commented on src/components/fields/UnitCountShorthandField.js
> -		this.promiseTimestamp = timestamp;
Can you elaborate why these were removed? Now if the response for the last sent request arrives sooner than some previous one, the previous response will overwrite the last request. Some debounce mechanic would be optimal here, but that's outside of this PR's scope.

2021-03-09 11:01 UTC, aorin commented
Didn't know about submit hooks, thanks for pointing that out. Reverted the first commit and changed it to use submit hooks. Seems to work well, does it look ok?

2021-03-09 11:38 UTC, olzraiti approved these changes
Looks good!

2021-03-09 11:38 UTC, merged